blueprint:
  name: E-Paper Display – 4 Quadranten FINAL
  description: >
    4 Sensoren im Quadranten-Layout für E-Paper Displays.
    Mit Displaygröße (2,66 / 2,9 / 3,5 Zoll) und eigener Einheit pro Sensor.
  domain: automation
  homeassistant:
    min_version: 2023.8.0

  input:
    display_size:
      name: Displaygröße
      description: Welche Displaygröße wird verwendet?
      default: "2.9"
      selector:
        select:
          options:
            - label: 2,66 Zoll
              value: "2.66"
            - label: 2,9 Zoll
              value: "2.9"
            - label: 3,5 Zoll
              value: "3.5"

    epaper_device:
      name: E-Paper Display
      description: Zielgerät
      selector:
        device:
          integration: open_epaper_link

    display_title:
      name: Display Titel
      default: "Sensor Übersicht"
      selector:
        text:

    # ---------- SENSOR 1 ----------
    sensor_1:
      name: Sensor 1 (oben links)
      selector:
        entity:
          domain: sensor
    sensor_1_unit:
      name: Einheit Sensor 1
      default: "°C"
      selector:
        text:

    # ---------- SENSOR 2 ----------
    sensor_2:
      name: Sensor 2 (oben rechts)
      selector:
        entity:
          domain: sensor
    sensor_2_unit:
      name: Einheit Sensor 2
      default: "°C"
      selector:
        text:

    # ---------- SENSOR 3 ----------
    sensor_3:
      name: Sensor 3 (unten links)
      selector:
        entity:
          domain: sensor
    sensor_3_unit:
      name: Einheit Sensor 3
      default: "°C"
      selector:
        text:

    # ---------- SENSOR 4 ----------
    sensor_4:
      name: Sensor 4 (unten rechts)
      selector:
        entity:
          domain: sensor
    sensor_4_unit:
      name: Einheit Sensor 4
      default: "bar"
      selector:
        text:

variables:
  s1: !input sensor_1
  s2: !input sensor_2
  s3: !input sensor_3
  s4: !input sensor_4
  u1: !input sensor_1_unit
  u2: !input sensor_2_unit
  u3: !input sensor_3_unit
  u4: !input sensor_4_unit

trigger:
  - platform: state
    entity_id:
      - !input sensor_1
      - !input sensor_2
      - !input sensor_3
      - !input sensor_4

action:
  - service: open_epaper_link.drawcustom
    data:
      background: white
      payload:
        - type: text
          value: !input display_title
          x: 10
          y: 5
          size: 14

        - type: text
          value: "{{ states(s1) }} {{ u1 }}"
          x: 10
          y: 30
          size: 14

        - type: text
          value: "{{ states(s2) }} {{ u2 }}"
          x: 160
          y: 30
          size: 14

        - type: text
          value: "{{ states(s3) }} {{ u3 }}"
          x: 10
          y: 80
          size: 14

        - type: text
          value: "{{ states(s4) }} {{ u4 }}"
          x: 160
          y: 80
          size: 14

    target:
      device_id: !input epaper_device

mode: single
