blueprint:
  name: E-Paper Display – 4 Quadranten mit Displaygröße
  description: >
    4-Quadranten-Layout für E-Paper Displays mit auswählbarer Displaygröße
    (2,66" / 2,9" / 3,5") und individueller Einheit pro Sensor.
  domain: automation
  homeassistant:
    min_version: 2023.8.0

  input:
    # ---------- DISPLAY ----------
    display_size:
      name: Displaygröße
      description: Welche Displaygröße wird verwendet?
      default: "2.9"
      selector:
        select:
          options:
            - label: 2,66 Zoll
              value: "2.66"
            - label: 2,9 Zoll
              value: "2.9"
            - label: 3,5 Zoll
              value: "3.5"

    display_title:
      name: Display Titel
      default: "Sensor Übersicht"
      selector:
        text:

    epaper_device:
      name: E-Paper Display
      description: Zielgerät
      selector:
        device:
          integration: open_epaper_link

    ttl:
      name: TTL (Sekunden)
      default: 600
      selector:
        number:
          min: 60
          max: 3600
          step: 60
          unit_of_measurement: "s"

    # ---------- SENSOR 1 ----------
    sensor_1:
      name: Sensor 1 (oben links)
      selector:
        entity:
          domain: sensor
    sensor_1_label:
      default: "Sensor 1"
      selector:
        text:
    sensor_1_icon:
      default: mdi:thermometer
      selector:
        icon:
    sensor_1_unit:
      default: "°C"
      selector:
        text:

    # ---------- SENSOR 2 ----------
    sensor_2:
      name: Sensor 2 (oben rechts)
      selector:
        entity:
          domain: sensor
    sensor_2_label:
      default: "Sensor 2"
      selector:
        text:
    sensor_2_icon:
      default: mdi:thermometer
      selector:
        icon:
    sensor_2_unit:
      default: "°C"
      selector:
        text:

    # ---------- SENSOR 3 ----------
    sensor_3:
      name: Sensor 3 (unten links)
      selector:
        entity:
          domain: sensor
    sensor_3_label:
      default: "Sensor 3"
      selector:
        text:
    sensor_3_icon:
      default: mdi:thermometer
      selector:
        icon:
    sensor_3_unit:
      default: "°C"
      selector:
        text:

    # ---------- SENSOR 4 ----------
    sensor_4:
      name: Sensor 4 (unten rechts)
      selector:
        entity:
          domain: sensor
    sensor_4_label:
      default: "Druck"
      selector:
        text:
    sensor_4_icon:
      default: mdi:car-brake-low-pressure
      selector:
        icon:
    sensor_4_unit:
      default: "bar"
      selector:
        text:

    threshold_low:
      name: Unterer Schwellenwert
      default: 30
      selector:
        number:
          min: 0
          max: 100

    normal_color:
      default: black
      selector:
        select:
          options:
            - black
            - red
            - white

    alert_color:
      default: red
      selector:
        select:
          options:
            - red
            - black
            - white

    divider_color:
      default: red
      selector:
        select:
          options:
            - red
            - black
            - white

variables:
  s1: !input sensor_1
  s2: !input sensor_2
  s3: !input sensor_3
  s4: !input sensor_4
  u1: !input sensor_1_unit
  u2: !input sensor_2_unit
  u3: !input sensor_3_unit
  u4: !input sensor_4_unit
  threshold: !input threshold_low
  normal_col: !input normal_color
  alert_col: !input alert_color
  size: !input display_size

  layout: >
    {% if size == '2.66' %}
      {{ dict(w=264, h=176, icon=38, val=14, label=12, title_x=40, mid_x=132, mid_y=88) }}
    {% elif size == '3.5' %}
      {{ dict(w=384, h=240, icon=55, val=18, label=15, title_x=95, mid_x=192, mid_y=120) }}
    {% else %}
      {{ dict(w=296, h=128, icon=45, val=15, label=13, title_x=43, mid_x=148, mid_y=64) }}
    {% endif %}

trigger:
  - platform: state
    entity_id:
      - !input sensor_1
      - !input sensor_2
      - !input sensor_3
      - !input sensor_4

action:
  - service: open_epaper_link.drawcustom
    data:
      background: white
      ttl: !input ttl
      payload:

        # Titel
        - type: text
          value: !input display_title
          x: "{{ layout.title_x }}"
          y: 5
          size: "{{ layout.label }}"

        # Trennlinien
        - type: line
          x_start: "{{ layout.mid_x }}"
          y_start: 15
          x_end: "{{ layout.mid_x }}"
          y_end: "{{ layout.h - 10 }}"
          color: !input divider_color

        - type: line
          x_start: 10
          y_start: "{{ layout.mid_y }}"
          x_end: "{{ layout.w - 10 }}"
          y_end: "{{ layout.mid_y }}"
          color: !input divider_color

        # -------- Q1 --------
        - type: icon
          value: !input sensor_1_icon
          x: 5
          y: 20
          size: "{{ layout.icon }}"
          color: "{{ alert_col if states(s1)|float(0) < threshold else normal_col }}"
        - type: text
          value: !input sensor_1_label
          x: "{{ layout.icon + 10 }}"
          y: 30
          size: "{{ layout.label }}"
        - type: text
          value: "{{ states(s1)|float|round(1) }} {{ u1 }}"
          x: "{{ layout.icon + 10 }}"
          y: 50
          size: "{{ layout.val }}"

        # -------- Q2 --------
        - type: icon
          value: !input sensor_2_icon
          x: "{{ layout.mid_x + 5 }}"
          y: 20
          size: "{{ layout.icon }}"
          color: "{{ alert_col if states(s2)|float(0) < threshold else normal_col }}"
        - type: text
          value: !input sensor_2_label
          x: "{{ layout.mid_x + layout.icon + 10 }}"
          y: 30
          size: "{{ layout.label }}"
        - type: text
          value: "{{ states(s2)|float|round(1) }} {{ u2 }}"
          x: "{{ layout.mid_x + layout.icon + 10 }}"
          y: 50
          size: "{{ layout.val }}"

        # -------- Q3 --------
        - type: icon
          value: !input sensor_3_icon
          x: 5
          y: "{{ layout.mid_y + 10 }}"
          size: "{{ layout.icon }}"
          color: "{{ alert_col if states(s3)|float(0) < threshold else normal_col }}"
        - type: text
          value: !input sensor_3_label
          x: "{{ layout.icon + 10 }}"
          y: "{{ layout.mid_y + 20 }}"
          size: "{{ layout.label }}"
        - type: text
          value: "{{ states(s3)|float|round(1) }} {{ u3 }}"
          x: "{{ layout.icon + 10 }}"
          y: "{{ layout.mid_y + 40 }}"
          size: "{{ layout.val }}"

        # -------- Q4 --------
        - type: icon
          value: !input sensor_4_icon
          x: "{{ layout.mid_x + 5 }}"
          y: "{{ layout.mid_y + 10 }}"
          size: "{{ layout.icon }}"
          color: "{{ alert_col if states(s4)|float(0) < threshold else normal_col }}"
        - type: text
          value: !input sensor_4_label
          x: "{{ layout.mid_x + layout.icon + 10 }}"
          y: "{{ layout.mid_y + 20 }}"
          size: "{{ layout.label }}"
        - type: text
          value: "{{ states(s4)|float|round(2) }} {{ u4 }}"
          x: "{{ layout.mid_x + layout.icon + 10 }}"
          y: "{{ layout.mid_y + 40 }}"
          size: "{{ layout.val }}"

    target:
      device_id: !input epaper_device

mode: single
