blueprint:
  name: E-Paper Display – TEST Displaygröße
  domain: automation
  input:
    display_size:
      name: Displaygröße
      description: Test-Auswahl
      default: "2.9"
      selector:
        select:
          options:
            - label: 2,66 Zoll
              value: "2.66"
            - label: 2,9 Zoll
              value: "2.9"
            - label: 3,5 Zoll
              value: "3.5"

    epaper_device:
      name: E-Paper Display
      selector:
        device:
          integration: open_epaper_link

trigger: []

action:
  - service: open_epaper_link.drawcustom
    data:
      background: white
      payload:
        - type: text
          value: "Displaygröße: {{ !input display_size }}"
          x: 10
          y: 10
          size: 14
    target:
      device_id: !input epaper_device

mode: single
